# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythings', '0010_auto_20160817_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
