# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mythings', '0011_auto_20160817_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 8, 17, 19, 55, 44, 927172, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
