# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythings', '0014_contact_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_lead',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
