# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythings', '0016_auto_20161201_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact_lead',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
