# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mythings', '0018_auto_20161202_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact_lead',
            name='name',
        ),
    ]
