# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mythings', '0019_auto_20161202_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_lead',
        ),
    ]
