# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 17:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mythings', '0020_delete_contact_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactentry',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 12, 2, 17, 55, 17, 618915, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactentry',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 12, 2, 17, 55, 25, 953947, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
