# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mythings', '0021_auto_20161202_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactentry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactentry',
            name='name',
        ),
    ]
